### ISSUE TITLE
Default reference to :latest means that user's tests aren't repeatable.

### ISSUE THREAD

**Issue by k-wall** [kroxylicious/kroxylicious-junit5-extension#143]
Currently, the framework use a default `:latest` tag in its references to the zookeeper and kafka native images.  As a user of the test framework, I expect test repeatability by default.  The latest tag means this isn't the case. A new version of kafka could be containerized, which could break spontaneously break tests.

The user already has the ability to override the version via the `Version` annotation, but this onerous on the user.   

https://github.com/kroxylicious/kroxylicious-junit5-extension/blob/3cd6816bfa71b0961e6eb7d4616af8d038c4b0be/impl/src/main/java/io/kroxylicious/testing/kafka/testcontainers/TestcontainersKafkaCluster.java#L74

**Comment by franvila** [comment]
From my point of view, pointing always to the latest version makes the tests more maintainable and in this case, kafka native versions are not changing every week, sometimes not even a month and it is more or less controlled.

I think that if we want to assure repeatability we have to force the `KAFKA_VERSION` environment variable to a certain value, because in my opinion we would miss the benefit of testing by default with the latest version and do the `fail fast` design. That is finding possible failures asap.

**Comment by SamBarker** [comment]
I've been trying for a week form a response to this. 

I think @k-wall is right we should be repeatable by default and depending on latest doesn't do that for us. However that cuts against the grain of most modern package management systems (see npm/github actions) hopefully that changes with people worrying much more about secure supply chains. 

For me the big problem with depending on latest is not the risk of un-expected changes upstream breaking things (thats bad) but the fact I can't retrospectively re-build anything. I can re-build a given SHA from the project history but I wont run the tests as they were at the time of that build because `:latest` could point at something entirely different. 

However I'm also wary of requiring us to make a code change every time there is a new upstream release of the image. 

Would it be enough to ensure that extension and kroxylicious executes the test suite with the env var set to a specific version based on a property in the pom (I would suggest based on our Kafka dependency but I'm guessing the versions will not align exactly).

That might work as compromise so that we don't force our views on repeatable builds on every downstream project?

**Comment by franvila** [comment]
> Would it be enough to ensure that extension and kroxylicious executes the test suite with the env var set to a specific version based on a property in the pom (I would suggest based on our Kafka dependency but I'm guessing the versions will not align exactly).

I agree with this solution, it won't compromise any upstream breaking changes and we can assure that always the tests for an specific release will run with the same version of the corresponding kafka native image.

I was thinking only about the future versions, not the past ones. These will be important for regression purposes and I agree this have to be fixed. But I suggest to use the `KAFKA_VERSION` environment variable instead of modifying the code every time a new kafka native version is released.

**Comment by k-wall** [comment]
I think we need stability by default, at least to the minor. Principle of Least Surprise and all that.  The fact that it is a container image reference rather than maven GAV ref doesn't matter - it is the same issue. If a user of the extension want to opt-out and live on the bleeding edge, fine, we can let them do that.   Maven lets you do that we a version range. 

> However I'm also wary of requiring us to make a code change every time there is a new upstream release of the image.

It that really so onerous?  Doesn't that mean we just need to automate more so it becomes easy..

Is there some way we can get dependabot to do the lifting for us?
https://github.blog/changelog/2022-11-16-dependabot-version-updates-for-docker-image-tags-in-kubernetes-manifests/

**Comment by robobario** [comment]
I'm with Keith, I want both fixed/reproducible builds and fast failure when a new Kafka is released.

option 1: set latest in extension, users opt into fixed version management with an ENV var.
- builds not reproducible by default
- clients who don't want `latest` will have to build their own automation based on updates to the quay image, not a great user experience, tools like `dependabot` clunky to use across ecosystems (docker -> java)
+ fast failure in user code, when a new native-kafka is released tests start failing
- no protection from a broken/incompatible native-kafka release, users discover this instead of junit-extension tests
+ cheap, don't have to go through the release process to m2 so often

option 2: set fixed version in extension by default, users opt into 'latest' if they want bleeding edge
- slower failure in user code if using fixed versions, have to wait for maven central release
+ users protected from failures like a non-starting/extension-incompatible kafka version
+ smoother integration with dependabot if the update is in maven central (in the same java ecosystem as the extension)
- more cost around having to run the maven central release
+ builds reproducible by default

So the best thing I see in option 2 that it's a better user story for keeping up-to-date, we can say "use dependabot if you want the latest tested kafka, or set this variable to use a bleeding-edge image".

**Comment by SamBarker** [comment]
Urgh, we dropped the ball on this. 

Volunteers to make option 2 a reality?

**Comment by SamBarker** [comment]
@k-wall that sounds ideal
